#
# This config-file is only needed for development. Instead of changing the url
# everytime you work locally on the project, you start both config-files, overwriting
# the first one with the development variables needed.
#
# Start development with › $ jekyll serve --config _config.yml,_config_dev.yml

url: 		'http://localhost:4000'
baseurl: 	''
urlimg: 	'http://localhost:4000/images/'

# See › https://github.com/jekyll/jekyll-gist#disabling-noscript-support
gist:
  noscript: false

# Gems
gems:
  #- jekyll-redirect-from
  - jekyll-sitemap

sass:
  # We specify the directory for Jekyll so we can use @imports.
  sass_dir: public/_sass

# Disable when not in production
google_analytics_tracking_id:

# Used › default.html front-matter and compress.html
# Options › http://jch.penibelst.de